name: My Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build stage
      run: echo "this is build stage"

    - name: Test stage
      run: echo "this is test stage"

    - name: Deploy stage
      run: echo "this is deploy stage"
